### ISSUE TITLE
[FEATURE] Build Basic Atoms

### ISSUE THREAD

**Issue by crown-3** [gsainfoteam/andromeda-fe#2]
# Todos
### Build Atoms
- [x] Card (+ with Gradient)
- [ ] Text with Gradient (in case of text gradient, it can be hard to apply to all the browsers)
- [ ] Text Button

### Fix Atoms
- [x] Rename textarea -> Textarea
- [x] Fix colors of textarea and input
